services:
  postgres:
    image: postgres:12.14-alpine
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
  pgadmin:
    environment:
      POSTGRES_DEFAULT_EMAIL: ${DATABASE_DEFAULT_EMAIL}
      POSTGRES_DEFAULT_PASSWORD: ${DATABASE_DEFAULT_PASSWORD}
    ports:
      - '5433:5432'