services:
  postgres:
    image: postgres:12.14-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-docker}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '5433:5432'
    restart: unless-stopped
  pgadmin:
    container_name: pg4admin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      POSTGRES_DEFAULT_EMAIL: ${POSTGRES_DEFAULT_EMAIL:-diemphuoc2626@gmail.com}
      POSTGRES_DEFAULT_PASSWORD: ${POSTGRES_DEFAULT_PASSWORD:-123}
    ports:
      - '5435:5432'

volumes:
  postgres: