spring:
  datasource:
    hikari:
      connection-timeout: 120000
      idle-timeout: 200000
      max-lifetime: 600000
      maximum-pool-size: 3
      minimum-idle: 2
      schema: user

  profiles:
    active: local
server:
  port: 8080


